name: 'run-dagger-py'
description: 'Action to run a dagger workflow, using the python SDK'
inputs:
  working_directory:
    description: 'The workflow folder where the dagger workflows leaves'
    required: true
    default: '.dagger'
  workflow:
    description: 'The workflow script to run, as specified in [tool.poetry.scripts]'
    required: true
    default: 'main'
  config_file:
    description: 'The firestarter config file path'
    required: true
    default: '.dagger/firestarter.yml'
  python_version:
    description: 'The python version to use'
    required: true
    default: '3.11'
  vars:
    description: 'The var arguments to pass to the workflow (in toml format)'
    required: false
    default: ""
  secrets:
    description: 'The secrets to pass to the workflow (in toml format)'
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry
      shell: bash

    - uses: actions/setup-python@v4
      with:
        python-version: '${{ inputs.python_version }}'
        cache: 'poetry'

    - run: poetry install --without=dev
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - id: run-dagger
      run: poetry run ${{ inputs.workflow }} --config_file ${{ inputs.config_file }} --secrets='${{ inputs.secrets }}' --args='${{ inputs.args }}'
      working-directory: ${{ inputs.working_directory }}
      shell: bash
